// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: matches/matches.proto

package matches

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MatchesClient is the client API for Matches service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchesClient interface {
	CreateMatch(ctx context.Context, in *CreateMatchRequest, opts ...grpc.CallOption) (*CreateMatchResponse, error)
	UpdateMatch(ctx context.Context, in *UpdateMatchRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetMatchById(ctx context.Context, in *GetMatchByIdRequest, opts ...grpc.CallOption) (*GetMatchByIdResponse, error)
	GetMatchesByIds(ctx context.Context, in *GetMatchesByIdsRequest, opts ...grpc.CallOption) (*GetMatchesByIdsResponse, error)
}

type matchesClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchesClient(cc grpc.ClientConnInterface) MatchesClient {
	return &matchesClient{cc}
}

func (c *matchesClient) CreateMatch(ctx context.Context, in *CreateMatchRequest, opts ...grpc.CallOption) (*CreateMatchResponse, error) {
	out := new(CreateMatchResponse)
	err := c.cc.Invoke(ctx, "/Matches/CreateMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchesClient) UpdateMatch(ctx context.Context, in *UpdateMatchRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Matches/UpdateMatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchesClient) GetMatchById(ctx context.Context, in *GetMatchByIdRequest, opts ...grpc.CallOption) (*GetMatchByIdResponse, error) {
	out := new(GetMatchByIdResponse)
	err := c.cc.Invoke(ctx, "/Matches/GetMatchById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchesClient) GetMatchesByIds(ctx context.Context, in *GetMatchesByIdsRequest, opts ...grpc.CallOption) (*GetMatchesByIdsResponse, error) {
	out := new(GetMatchesByIdsResponse)
	err := c.cc.Invoke(ctx, "/Matches/GetMatchesByIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchesServer is the server API for Matches service.
// All implementations must embed UnimplementedMatchesServer
// for forward compatibility
type MatchesServer interface {
	CreateMatch(context.Context, *CreateMatchRequest) (*CreateMatchResponse, error)
	UpdateMatch(context.Context, *UpdateMatchRequest) (*empty.Empty, error)
	GetMatchById(context.Context, *GetMatchByIdRequest) (*GetMatchByIdResponse, error)
	GetMatchesByIds(context.Context, *GetMatchesByIdsRequest) (*GetMatchesByIdsResponse, error)
	mustEmbedUnimplementedMatchesServer()
}

// UnimplementedMatchesServer must be embedded to have forward compatible implementations.
type UnimplementedMatchesServer struct {
}

func (UnimplementedMatchesServer) CreateMatch(context.Context, *CreateMatchRequest) (*CreateMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMatch not implemented")
}
func (UnimplementedMatchesServer) UpdateMatch(context.Context, *UpdateMatchRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMatch not implemented")
}
func (UnimplementedMatchesServer) GetMatchById(context.Context, *GetMatchByIdRequest) (*GetMatchByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchById not implemented")
}
func (UnimplementedMatchesServer) GetMatchesByIds(context.Context, *GetMatchesByIdsRequest) (*GetMatchesByIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchesByIds not implemented")
}
func (UnimplementedMatchesServer) mustEmbedUnimplementedMatchesServer() {}

// UnsafeMatchesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchesServer will
// result in compilation errors.
type UnsafeMatchesServer interface {
	mustEmbedUnimplementedMatchesServer()
}

func RegisterMatchesServer(s grpc.ServiceRegistrar, srv MatchesServer) {
	s.RegisterService(&Matches_ServiceDesc, srv)
}

func _Matches_CreateMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchesServer).CreateMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Matches/CreateMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchesServer).CreateMatch(ctx, req.(*CreateMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Matches_UpdateMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchesServer).UpdateMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Matches/UpdateMatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchesServer).UpdateMatch(ctx, req.(*UpdateMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Matches_GetMatchById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchesServer).GetMatchById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Matches/GetMatchById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchesServer).GetMatchById(ctx, req.(*GetMatchByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Matches_GetMatchesByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchesByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchesServer).GetMatchesByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Matches/GetMatchesByIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchesServer).GetMatchesByIds(ctx, req.(*GetMatchesByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Matches_ServiceDesc is the grpc.ServiceDesc for Matches service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Matches_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Matches",
	HandlerType: (*MatchesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMatch",
			Handler:    _Matches_CreateMatch_Handler,
		},
		{
			MethodName: "UpdateMatch",
			Handler:    _Matches_UpdateMatch_Handler,
		},
		{
			MethodName: "GetMatchById",
			Handler:    _Matches_GetMatchById_Handler,
		},
		{
			MethodName: "GetMatchesByIds",
			Handler:    _Matches_GetMatchesByIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matches/matches.proto",
}
