# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matches.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmatches.proto\x1a\x1bgoogle/protobuf/empty.proto\":\n\x12\x43reateMatchRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0e\x63ompetition_id\x18\x02 \x01(\x05\"l\n\x12UpdateMatchRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0e\x63ompetition_id\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\x07\n\x05_nameB\x11\n\x0f_competition_id\"!\n\x13GetMatchByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x16GetMatchesByIdsRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x05\"!\n\x13\x43reateMatchResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"H\n\x14GetMatchByIdResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x63ompetition_id\x18\x03 \x01(\x05\"A\n\x17GetMatchesByIdsResponse\x12&\n\x07matches\x18\x01 \x03(\x0b\x32\x15.GetMatchByIdResponse2\x8a\x02\n\x07Matches\x12:\n\x0b\x43reateMatch\x12\x13.CreateMatchRequest\x1a\x14.CreateMatchResponse\"\x00\x12<\n\x0bUpdateMatch\x12\x13.UpdateMatchRequest\x1a\x16.google.protobuf.Empty\"\x00\x12=\n\x0cGetMatchById\x12\x14.GetMatchByIdRequest\x1a\x15.GetMatchByIdResponse\"\x00\x12\x46\n\x0fGetMatchesByIds\x12\x17.GetMatchesByIdsRequest\x1a\x18.GetMatchesByIdsResponse\"\x00\x42\x0eZ\x0cmain/matchesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matches_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014main/matches'
  _globals['_CREATEMATCHREQUEST']._serialized_start=46
  _globals['_CREATEMATCHREQUEST']._serialized_end=104
  _globals['_UPDATEMATCHREQUEST']._serialized_start=106
  _globals['_UPDATEMATCHREQUEST']._serialized_end=214
  _globals['_GETMATCHBYIDREQUEST']._serialized_start=216
  _globals['_GETMATCHBYIDREQUEST']._serialized_end=249
  _globals['_GETMATCHESBYIDSREQUEST']._serialized_start=251
  _globals['_GETMATCHESBYIDSREQUEST']._serialized_end=288
  _globals['_CREATEMATCHRESPONSE']._serialized_start=290
  _globals['_CREATEMATCHRESPONSE']._serialized_end=323
  _globals['_GETMATCHBYIDRESPONSE']._serialized_start=325
  _globals['_GETMATCHBYIDRESPONSE']._serialized_end=397
  _globals['_GETMATCHESBYIDSRESPONSE']._serialized_start=399
  _globals['_GETMATCHESBYIDSRESPONSE']._serialized_end=464
  _globals['_MATCHES']._serialized_start=467
  _globals['_MATCHES']._serialized_end=733
# @@protoc_insertion_point(module_scope)
